language: csharp
solution: CSSS.sln

matrix:
  include:
    - os: linux
      dist: bionic
      mono: latest
    - os: linux
      dist: xenial
      mono: latest

script:
  - xbuild /p:Configuration=Release CSSS.sln
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./CSSS.sln --config=Release --skipnontestassemblies
