#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 0.3.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image:
  - Ubuntu
  - Ubuntu1804
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

#---------------------------------#
#       build configuration       #
#---------------------------------#
platform: Any CPU

configuration: Release

before_build: nuget restore

build:
  project: CSSS.sln
  verbosity: normal

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off

test_script: nunit3-console.exe .\CSSS.sln --config=Release --skipnontestassemblies --result=myresults.xml;format=AppVeyor
